name: Create GitHub release

on:
  create:
    tags:
      - "*[0-9]+.[0-9]+.[0-9]*"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    env:
      # Check the changes in these files/directories to build automatically the release notes
      PATHS_FOR_RELEASE_NOTES: "box.json.dist composer.json bin/ src/"
      # Its value will be set by the action (if release-like tag is created)
      VERSION: ""
      # Its value will be set by the action (if release-like tag is created)
      PRERELEASE: ""
      # The version of PHP to be used here
      INSTALLER_PHP_VERSION: '7.3'
      # The minimum PHP version the built phar should support
      PHAR_PHP_VERSION: '7.1'
      # The version of Box to be used
      BOX_VERSION: 3.13.0
    steps:
      - name: Check tag format
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        run: |
          VERSION="$(printf '%s' "$GITHUB_REF" | sed -E 's/^refs\/tags\/v?([0-9]+\.[0-9]+\.[0-9]+.*)$/\1/')"
          if printf '%s' "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]'; then
            case "$VERSION" in
              *dev* | *snap* | *[Aa]* | *[Bb]* | *[Rr][Cc]*)
                PRERELEASE=true
                ;;
              *)
                PRERELEASE=false
                ;;
            esac
            printf 'The tag %s is for version %s\n' "${GITHUB_REF#refs/tags/}" "$VERSION"
            printf 'Prelease: %s\n' "$PRERELEASE"
            printf 'VERSION=%s\n' "$VERSION" >> "$GITHUB_ENV"
            printf 'PRERELEASE=%s\n' "$PRERELEASE" >> "$GITHUB_ENV"
          else
            printf 'The ref %s is not for a version\n' "$GITHUB_REF"
          fi
      - name: Checkout
        if: env.VERSION != ''
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup PHP
        if: env.VERSION != ''
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.INSTALLER_PHP_VERSION }}
          tools: composer:v2
          coverage: none
          ini-values: phar.readonly=0
      - name: Configure environment
        run: composer config platform.php "$PHAR_PHP_VERSION"
      - name: Install Composer dependencies
        if: env.VERSION != ''
        run: composer update --no-dev --no-progress --optimize-autoloader --ansi --no-interaction --no-cache
      - name: Download Box
        if: env.VERSION != ''
        run: curl -Lf -o box.phar "https://github.com/box-project/box/releases/download/$BOX_VERSION/box.phar"
      - name: Create the PHAR file
        if: env.VERSION != ''
        run: php box.phar compile --ansi --no-interaction
      - name: Check if the PHAR file works
        run: ./ccm.phar list --ansi
      - name: Build release notes
        if: env.VERSION != ''
        run: |
          CURRENT_TAG_FOUND=n
          PREVIUOS_TAG=
          RELEASE_NOTES=
          for TAG in $(git tag --list --sort=-version:refname); do
            if printf '%s' "$TAG" | grep -Eq '^v?[0-9]+\.[0-9]+\.[0-9]+'; then
              if test $CURRENT_TAG_FOUND = n; then
                if test "$TAG" = "${GITHUB_REF#refs/tags/}"; then
                  CURRENT_TAG_FOUND=y
                fi
              else
                PREVIUOS_TAG="$TAG"
                break
              fi
            fi
          done
          if test $CURRENT_TAG_FOUND = n; then
            echo 'Unable to build the release notes (current tag not found)'
          elif test -z "$PREVIUOS_TAG"; then
            echo 'Unable to build the release notes (previous release tag not found)'
          else
            RELEASE_NOTES="$(git log --format='- %s' --no-merges --reverse "refs/tags/$PREVIUOS_TAG...$GITHUB_REF" -- $PATHS_FOR_RELEASE_NOTES)"
            if test -z "$RELEASE_NOTES"; then
              printf 'Unable to build the release notes (empty commit list since %s)\n' "$PREVIUOS_TAG"
            else
              printf 'Detected release notes since %s:\n%s\n' "$PREVIUOS_TAG" "$RELEASE_NOTES"
            fi
          fi
          if test -z "$RELEASE_NOTES"; then
            RELEASE_NOTES='n/a'
          fi
          printf '%s' "$RELEASE_NOTES" >new-release-notes.txt
      - name: Publish release
        if: env.VERSION != ''
        uses: softprops/action-gh-release@v1
        with:
          body_path: new-release-notes.txt
          draft: false
          prerelease: ${{ env.PRERELEASE }}
          files: >
            ccm.phar
          name: v${{ env.VERSION }}
          fail_on_unmatched_files: true
