name: PHPUnit

on: [push, pull_request]

jobs:
  build-lowest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_extensions: mbstring dom xml intl
          configuration: phpunit.xml.dist
          args: --coverage-text
          php_version: 7.1
          version: 7

  build-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml.dist
          args: --coverage-text
