name: Psalm

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          coverage: none

      - name: Install Psalm
        run: |
          composer global require vimeo/psalm --prefer-dist --ansi --no-interaction --no-cache --dev
          PATH=$(composer global config bin-dir --absolute --quiet):$PATH
          psalm --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: composer config platform.php '7.1'

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-cache

      - name: Run Psalm
        run: psalm --taint-analysis --show-info=true --output-format=github --report=results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
